import { Router } from "express";
import healthRouter from "./health";
import suppliesRouter from "./supplies";
import usageLogsRouter from "./usage-logs";
import dashboardRouter from "./dashboard";
import classroomsRouter from "./classrooms";
import authRouter from "./auth";
import usersRouter from "./users";
import requestsRouter from "./requests";
import notificationsRouter from "./notifications";
import reportsRouter from "./reports";
import classroomSuppliesRouter from "./classroom-supplies";
const router = Router();
router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/supplies", suppliesRouter);
router.use("/usage-logs", usageLogsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/classrooms", classroomsRouter);
router.use("/requests", requestsRouter);
router.use("/notifications", notificationsRouter);
router.use("/reports", reportsRouter);
router.use("/classroom-supplies", classroomSuppliesRouter);
export default router;
